### ISSUE TITLE
lack of responsive (i.e. auto-scaling) <div> sizing resulting in Zero height container <div>

### ISSUE THREAD

**Issue by LeadDreamer** [thomhines/square1#1]
I notice you expect a fixed div size to fit the images into (either height or width) - side effect being when you have a more responsive application (i.e. scaling to fit aspect ration), there is no size set on the enclosing <div>.  When the images is used as a *background*, the <div> ends up with no height: property, hence ends up height: 0.

I'll probably edit the code to check for this situation, and use aspect ratio info from the image (scaled to fit whichever maxwidth/maxheight may be set).  Obviously, unless the user wants to *allow* for huge images, *some* sort of max setting is needed (even if by %).  I *can* fork and create a pull request, *if* you're interested in the solution, else I'll just keep it on my own.

**Comment by thomhines** [comment]
That's a great point. Most use cases I was considering were based on the assumption that the slider would be placed somewhere there's a fixed height. I had considered at one point using the size of the image as the default size for the slider but decided against it since I built square1 to be able to work with lots of different image sizes and aspect ratios together. 

Don't send a pull request, but if you're willing to share what you end up doing, I might work some of your ideas into the code. And, at the very least, I will update the code with a default height so that it's not 0px tall if someone hasn't set a height yet. :)

Thanks for letting me know and offering the help!

**Comment by LeadDreamer** [comment]
Actually, while I haven't forked the repository yet, I have already solved
the issue - and in a fully responsive way (i.e. it scales with browser
window size).  It isn't actually *my* discovery - I got it from others - it
does work very well.  I have it currently implemented on norosesjewelry.com
(although the graphic designer just chose to only have one slide, so it's
not as obvious)

As you already know, an "absolute" positioned div does not influence the
size of it's parent, so the parent doesn't expand to hold the absolute
positioned child.

BUT - you *can* set the parent to a percentage width (standard for a flex
grid), *and* you can set the child to width: 100%. - and it will expand to
the with of the parent. Alas, there is no height information, really, so
the parent height remains 0, and the properly scaled child "overflows" -
but invisibly.  BUT there is an ancient browser bug to the rescue!

setting PADDING to a percentage is *always* relative to *width* - even
padding-top.  so the "trick" to a responsive image container is to set the
child width: 100%, and set the parent padding-top: (aspect_ratio)% - i.e.
for a square image, padding-top: 100%; for a 2000x700 image (my slides, as
a matter of fact) padding-top: 35%.  The padding effectively sets a height
for the parent div - but it scales with the relative width, maintaining
aspect ratio.

In my application of your slider, I have the *first* slide img as src=, and
the *others* as data-src= - accomplishing the lazy-load I needed for
performance.  Also, having the first image live minimizes "jump" on-load.
When the slides are switched (jump_to_slide), I calculate the aspect ratio
- $(image selector).naturalHeight/$(image selector).naturalWidth - and
apply that to the padding-top of the parent container.

In my application, the slides have the same aspect ratio, so there is no
shift when they load, but it would be easy to animate/smooth if needed.

Also, *if* someone wants a fixed *height*, easy enough to change code to
scale the *width* instead of the *padding*.  I'll have to check how much
some of my own CSS is "assisting" with this, but I can send along my
modified square1.js if you like.  Selfishly,I'd love to see it
incorporated, since I don't have a minimizer set up.

I can fairly easily fork & update so you can see the diff on github, or I
can diff locally and simply send you the changes.


Tracy

**Comment by thomhines** [comment]
Thanks for all of the great info, Tracy! I hadn't even thought to use the padding trick (I guess I wasn't thinking of this use case enough), but that's an easy enough solution. 

And thanks for the offer to send your code! No need to diff it for me. I have a diff-er and a minifier in VS Code, so I could see the changes and incorporate them easily enough. I'd love to see what you've done and I'll try to work it in if it fits well with what I'm aiming for on this project. At the very least, I need to solve the problem of what happens if a developer doesn't set a height for the slider in their CSS so that there's at least something visible.

Also, good call on not lazy-loading the first image in a set. That's what I do, too, and I should probably make a note of it in the docs. :)

**Comment by LeadDreamer** [comment]
Attached the .js (as .txt to get permission)

The only other change is I over-rode some of your CSS; specifically:

.square1 img {
display: none;
}

is over-ridden with:

.flexslider .slides img {
    max-width: 100%;
    margin: 0 auto;
    display: block;
}

Your code takes care of adding display: none as needed.

[square1.txt](https://github.com/thomhines/square1/files/5037536/square1.txt)

**Comment by LeadDreamer** [comment]
Net result before the js runs is (designer dropped it to one image for now)

<div class="squareslider flexslider" id="heroSlider">
  <div class="flex-viewport">
    <div class="slides">
      <a href="https://norosesjewelry.com/products/posie-solitaire-peridot-august-birthstone-ring?variant=32488410447919" title="summertime posie solitaire ring artisan jewelry los angeles">
        <img src="//cdn.shopify.com/s/files/1/0886/9818/t/33/assets/slide_1.jpg?v=12746469077439185802" alt="summertime posie solitaire ring artisan jewelry los angeles" />
      </a>
    </div>
  </div>
</div>

**Comment by LeadDreamer** [comment]
Net result before js runs is:

`<div class="squareslider flexslider" id="heroSlider">
  <div class="flex-viewport">
    <div class="slides">
      <a href="https://norosesjewelry.com/products/posie-solitaire-peridot-august-birthstone-ring?variant=32488410447919" title="summertime posie solitaire ring artisan jewelry los angeles">
        <img src="//cdn.shopify.com/s/files/1/0886/9818/t/33/assets/slide_1.jpg?v=12746469077439185802" alt="summertime posie solitaire ring artisan jewelry los angeles" />
      </a>
      <a href="https://norosesjewelry.com/collections/14k-gold-18k-gold" title="14k Gold Jewelry 18k Gold Jewelry">
        <img data-src="//cdn.shopify.com/s/files/1/0886/9818/t/33/assets/slide_2.jpg?v=6770813193628709746" alt="14k Gold Jewelry 18k Gold Jewelry" />
      </a>
      <a href="https://norosesjewelry.com/collections/carla-de-la-cruz" title="Carla de la Cruz Zodiac Pendants">
        <img data-src="//cdn.shopify.com/s/files/1/0886/9818/t/33/assets/slide_3.jpg?v=269076738913518053" alt="Carla de la Cruz Zodiac Pendants" />
      </a>
    </div>
  </div>
</div>`

**Comment by LeadDreamer** [comment]
Net result before js runs is:

    <div class="squareslider flexslider" id="heroSlider">
      <div class="flex-viewport">
        <div class="slides">
          <a href="https://norosesjewelry.com/products/posie-solitaire-peridot-august-birthstone-ring?variant=32488410447919" title="summertime posie solitaire ring artisan jewelry los angeles">
            <img src="//cdn.shopify.com/s/files/1/0886/9818/t/33/assets/slide_1.jpg?v=12746469077439185802" alt="summertime posie solitaire ring artisan jewelry los angeles" />
          </a>
          <a href="https://norosesjewelry.com/collections/14k-gold-18k-gold" title="14k Gold Jewelry 18k Gold Jewelry">
            <img data-src="//cdn.shopify.com/s/files/1/0886/9818/t/33/assets/slide_2.jpg?v=6770813193628709746" alt="14k Gold Jewelry 18k Gold Jewelry" />
          </a>
          <a href="https://norosesjewelry.com/collections/carla-de-la-cruz" title="Carla de la Cruz Zodiac Pendants">
            <img data-src="//cdn.shopify.com/s/files/1/0886/9818/t/33/assets/slide_3.jpg?v=269076738913518053" alt="Carla de la Cruz Zodiac Pendants" />
          </a>
        </div>
      </div>
    </div>

**Comment by thomhines** [comment]
Got it! I'll look through these soon and I'll let you know if I update the code. Thanks again!

**Comment by thomhines** [comment]
Sorry for the wait! I _finally_ got around to working on this. I didn't use your code specifically since it doesn't completely line up with the type of responsiveness use cases I'm designing for, but I LOVE your solution and think's really clever. 

All that said, you brought up an important issue about the slider not having a default height and I borrowed your idea of having the slider size itself to proportional height of the first image if nothing else is dictating the height. It's not ideal, but at least it means the sliders won't be 0px tall if the developer doesn't set a height. :) 

Thank you again for commenting and sharing your code!
