### ISSUE TITLE
Images with different sizes

### ISSUE THREAD

**Issue by EaBw** [thomhines/square1#2]
Hi, if loading images with different sizes, e.g. portrait and landscape the second is cut. The sizes should be the real ones, limited by width-max.
Regards, EaBw

**Comment by thomhines** [comment]
Hi! Thanks for writing. I'm not sure I'm understanding correctly, but it's possible that the slider does what you're talking about already. If you want to make sure the entire image is shown, try the `fill_mode: 'contain'` setting. The default setting is 'cover' which crops images on either the top and bottom or sides in order to fill the slideshow area completely regardless of image size. 

And if you're hoping that the slideshow will adjust in size to the various image sizes, well... you might just need a different slider. :) The slider is more intended for use cases where the slider shape and size is prioritized over the shape and size of the image.
